# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - uk-sns-police-data

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://virtualsimon.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_b8dd845cbe934777ae2f89f2a4ee414f }}
        password: ${{ secrets.AzureAppService_ContainerPassword_ed3bc0bf7e014108869f038d35738c61 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: virtualsimon.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_b8dd845cbe934777ae2f89f2a4ee414f }}/uk-sns-police-data:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'uk-sns-police-data'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_83f36747ac3b4a01aa78de5069cc4b17 }}
        images: 'virtualsimon.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_b8dd845cbe934777ae2f89f2a4ee414f }}/uk-sns-police-data:${{ github.sha }}'